# Generated by Django 5.2.7 on 2025-11-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_guest_can_control_volume'),
        ('spotify', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'room', 'song_id')},
        ),
    ]
