# Generated by Django 5.2.7 on 2025-11-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_can_control_volume',
            field=models.BooleanField(default=False),
        ),
    ]
